/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function applyTransform(targetJson: string, path: string, valueJson: string): string

export declare function applyTransformCtx(ctxJson: string, path: string, valueJson: string): string

export declare function canonicalJson(valueJson: string): string

export declare function composeAggregate(compositionJson: string, verdictsJson: string): string

export declare function contextIdentity(ctxJson: string): string

export declare function ctkAssert(vectorJson: string, recordedJson: string, runRecordJson: string): string

export declare function ctkScriptedIntercept(rulesJson: string, ctxJson: string): string

export declare function ctkScriptedResolve(rulesJson: string, ctxJson: string, identity: string): string

export declare function ctkShouldSkip(vectorJson: string, harnessCapsJson: string): string

/**
 * Steps 2 to 10 of §7.7.6 against the wrapper's host description
 * (`{surface, identity_providers, approval_resolvers,
 * approval_redactors, kinds}`). Returns the resolved declaration JSON.
 */
export declare function declarationResolve(documentJson: string, hostJson: string): string

/**
 * Steps 2 to 8 of §7.7.6 against a code surface alone, no registry:
 * what the CTK runner needs to read a harness's own document
 * (§7.7.9). A surface that does not parse or that the core rejects is
 * a wrapper defect and comes back as `marshal_error`, never as a
 * refusal of the document.
 */
export declare function declarationResolveSurface(documentJson: string, surfaceJson: string): string

/**
 * Steps 2 to 7 of §7.7.6 over JSON text. Returns the validated
 * document as JSON (verbatim, `$schema` included).
 */
export declare function declarationValidate(documentJson: string): string

/** `{"current": "...", "supported": [...]}` (§7.7.2). */
export declare function declarationVersions(): string

export declare function finalize(ctxJson: string, verdictJson: string, mode: string, optionsJson: string): string

export declare function specVersion(): string

/** §4/§6.3: envelope validation (fail closed, value-free detail). */
export declare function validateEnvelope(ctxJson: string): string

export declare function validateTransformCtx(ctxJson: string, path: string, valueJson: string): string

export declare function validateVerdict(verdictJson: string): string
