// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//! Cross-SDK golden vectors for §10 canonical JSON and context identity.
//!
//! `conformance/golden/identity.json` is generated by
//! `scripts/gen-golden-identity.py` from this crate; every language
//! binding runs an equivalent test against the same file. A divergence
//! here means an SDK is not calling into the Rust core.

use agent_hooks::{canonical_json, context_identity, AgentContext};
use serde_json::Value;

fn load() -> Vec<Value> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../conformance/golden/identity.json");
    let doc: Value = serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    doc["fixtures"].as_array().unwrap().clone()
}

#[test]
fn golden_canonical_json() {
    for f in load() {
        if f["expect"].get("error").is_some() {
            continue; // negative fixture: asserted via identity below
        }
        let got = canonical_json(&f["ctx"]);
        assert_eq!(
            got,
            f["expect"]["canonical_json"].as_str().unwrap(),
            "canonical_json mismatch for {}",
            f["id"]
        );
    }
}

#[test]
fn golden_context_identity() {
    for f in load() {
        let ctx: AgentContext = serde_json::from_value(f["ctx"].clone()).unwrap();
        if f["expect"].get("error").is_some() {
            // §10.2: out-of-domain contexts fail closed — never a
            // real-looking identity.
            let (e, _) = context_identity(&ctx)
                .expect_err("negative fixture must be rejected");
            assert_eq!(e.to_string(), "host_error:context_invalid", "{}", f["id"]);
            continue;
        }
        let got = context_identity(&ctx).expect("golden fixtures are valid I-JSON");
        assert_eq!(
            got,
            f["expect"]["context_identity"].as_str().unwrap(),
            "context_identity mismatch for {}",
            f["id"]
        );
    }
}

#[test]
fn golden_provider_rejects_beyond_2_53() {
    // §10.2 input domain: the jcs-sha256 provider fails closed on
    // integral values outside ±(2^53−1) instead of silently rounding.
    let mut f = load().into_iter().next().unwrap();
    f["ctx"]["target"] = serde_json::json!({"id": 9_007_199_254_740_993_i64});
    let ctx: AgentContext = serde_json::from_value(f["ctx"].clone()).unwrap();
    let (e, detail) = context_identity(&ctx).unwrap_err();
    assert_eq!(e.to_string(), "host_error:context_invalid");
    assert!(detail.contains("string-encode 64-bit identifiers"), "{detail}");
}

#[test]
fn golden_l2_l3_stripped() {
    let fs = load();
    let g05 = fs.iter().find(|f| f["id"] == "G-05-l2-l3-stripped").unwrap();
    let g05b = fs.iter().find(|f| f["id"] == "G-05b-l2-l3-baseline").unwrap();
    assert_eq!(
        g05["expect"]["context_identity"], g05b["expect"]["context_identity"],
        "L2/L3 fields must not affect context_identity (§10.2)"
    );
}
