# Type stubs for the PyO3 native module (agent_hooks._core).
# All functions take/return UTF-8 JSON strings.

SPEC_VERSION: str

class AgentHooksCoreError(ValueError):
    """Raised by every _core function on failure. ``.code`` is the §11
    ``host_error:*`` wire string."""
    code: str

def spec_version() -> str: ...
def canonical_json(value_json: str, /) -> str: ...
def context_identity(ctx_json: str, /) -> str: ...
def validate_verdict(verdict_json: str, /) -> str: ...
def apply_transform(target_json: str, path: str, value_json: str, /) -> str: ...
def apply_transform_ctx(ctx_json: str, path: str, value_json: str, /) -> str: ...
def validate_transform_ctx(ctx_json: str, path: str, value_json: str, /) -> str: ...
def finalize(ctx_json: str, verdict_json: str, mode: str, options_json: str, /) -> str: ...
def validate_envelope(ctx_json: str, /) -> str: ...
def compose_aggregate(composition_json: str, verdicts_json: str, /) -> str: ...

# CTK engine (§13.2)
def ctk_scripted_intercept(rules_json: str, ctx_json: str, /) -> str: ...
def ctk_scripted_resolve(rules_json: str, ctx_json: str, identity: str, /) -> str: ...
def ctk_should_skip(vector_json: str, harness_caps_json: str, /) -> str: ...
def ctk_assert(vector_json: str, recorded_json: str, run_record_json: str, /) -> str: ...
